#!/bin/bash
set -e

ORV='3.3'

# Download OpenRefine https://github.com/OpenRefine/OpenRefine/
wget -q -O openrefine.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/${ORV}/openrefine-linux-${ORV}.tar.gz
mkdir -p openrefine
tar -xzf openrefine.tar.gz -C openrefine --strip 1
rm openrefine.tar.gz
sed -i 's/#REFINE_AUTOSAVE_PERIOD=60/REFINE_AUTOSAVE_PERIOD=1440/' openrefine/refine.ini

# Download openrefine-client https://github.com/opencultureconsulting/openrefine-client
wget -q -O openrefine-client https://github.com/opencultureconsulting/openrefine-client/releases/download/v0.3.8/openrefine-client_0-3-8_linux
chmod +x openrefine-client
mkdir -p ~/.local/bin
mv openrefine-client ~/.local/bin/

# Install bash_kernel https://github.com/takluyver/bash_kernel
python -m bash_kernel.install

# Enable nbserverproxy for OpenRefine https://github.com/betatim/nbserverproxy
jupyter serverextension enable --py nbserverproxy
pip install -e.
jupyter serverextension enable  --user --py nbopenrefineproxy
jupyter nbextension     install --user --py nbopenrefineproxy
jupyter nbextension     enable  --user --py nbopenrefineproxy
